// Generated by CoffeeScript 1.6.3
(function() {
  var $mainCanvas, createCanvas, drawing, getWTPlugin, height, offscreenCtx, offscreenImg, onDraw, width;

  $mainCanvas = $('#canvas');

  width = $mainCanvas.width();

  height = $mainCanvas.height();

  getWTPlugin = function() {
    return document.getElementById('wtPlugin');
  };

  createCanvas = function(width, height) {
    var c;
    c = document.createElement('canvas');
    c.width = width;
    c.height = height;
    return c;
  };

  offscreenCtx = createCanvas(width, height).getContext('2d');

  offscreenCtx.fillRect(0, 0, width, height);

  offscreenImg = offscreenCtx.getImageData(0, 0, width, height);

  drawing = false;

  onDraw = function(e) {
    var col, data, i, ix, iy, lol, penAPI, pressure, x, y, _i, _j;
    x = e.pageX - $mainCanvas.position().left;
    y = e.pageY - $mainCanvas.position().top;
    if (!drawing) {
      return;
    }
    penAPI = getWTPlugin().penAPI;
    pressure = 0.0;
    if (penAPI) {
      pressure = penAPI.pressure;
    }
    lol = 5;
    col = Math.round((1 - pressure) * 255);
    data = offscreenImg.data;
    for (ix = _i = 0; 0 <= lol ? _i <= lol : _i >= lol; ix = 0 <= lol ? ++_i : --_i) {
      for (iy = _j = 0; 0 <= lol ? _j <= lol : _j >= lol; iy = 0 <= lol ? ++_j : --_j) {
        i = (x + ix + (y + iy) * width) * 4;
        data[i] = col;
        data[i + 1] = col;
        data[i + 2] = col;
        data[i + 3] = 0xff;
      }
    }
    offscreenCtx.putImageData(offscreenImg, 0, 0, x, y, lol, lol);
    return $mainCanvas[0].getContext('2d').drawImage(offscreenCtx.canvas, x, y, lol, lol, x, y, lol, lol);
  };

  $mainCanvas.mouseup(function(e) {
    return drawing = false;
  });

  $mainCanvas.mousedown(function(e) {
    drawing = true;
    return onDraw(e);
  });

  $mainCanvas.mousemove(function(e) {
    return onDraw(e);
  });

}).call(this);
