// Generated by CoffeeScript 1.6.3
(function() {
  var $can, createCanvas, height, offscreenCtx, offscreenImg, width;

  $can = $('#canvas')[0];

  width = $can.width;

  height = $can.height;

  createCanvas = function(width, height) {
    var c;
    c = document.createElement('canvas');
    c.width = width;
    c.height = height;
    return c;
  };

  offscreenCtx = createCanvas(width, height).getContext('2d');

  offscreenCtx.fillRect(0, 0, width, height);

  offscreenImg = offscreenCtx.getImageData(0, 0, width, height);

  $('#canvas').mousemove(function(e) {
    var data, i, ix, iy, lol, x, y, _i, _j, _ref;
    _ref = [e.clientX, e.clientY], x = _ref[0], y = _ref[1];
    lol = 10;
    data = offscreenImg.data;
    for (ix = _i = 0; 0 <= lol ? _i <= lol : _i >= lol; ix = 0 <= lol ? ++_i : --_i) {
      for (iy = _j = 0; 0 <= lol ? _j <= lol : _j >= lol; iy = 0 <= lol ? ++_j : --_j) {
        i = (x + ix + (y + iy) * width) * 4;
        data[i] = 0x10;
        data[i + 1] = ix * 10;
        data[i + 2] = iy * 10;
        data[i + 3] = 0xff;
      }
    }
    offscreenCtx.putImageData(offscreenImg, 0, 0, x, y, lol, lol);
    return $can.getContext('2d').drawImage(offscreenCtx.canvas, x, y, lol, lol, x, y, lol, lol);
  });

}).call(this);
