// Generated by CoffeeScript 1.6.3
var Core, assert;

assert = require('assert');

Core = require('../core');

describe('Rect', function() {
  return it('should intersect correctly', function() {
    var a, b;
    a = new Core.Rect(10, 20, 100, 100);
    b = new Core.Rect(20, 10, 100, 100);
    assert.equal(a.intersect(b).width, 90);
    assert.equal(b.intersect(a).width, 90);
    assert.equal(a.intersect(b).height, 90);
    assert.equal(b.intersect(a).height, 90);
    a = new Core.Rect(0, 0, 100, 100);
    b = new Core.Rect(200, 50, 100, 100);
    assert.equal(a.intersect(b).width, 0);
    return assert.equal(b.intersect(a).height, 50);
  });
});

describe('Vector', function() {
  it('should add and sub', function() {
    var va, vb;
    va = new Core.Vector(1, 2);
    vb = new Core.Vector(2, 3);
    assert.equal(va.add(vb).x, 3);
    assert.equal(va.add(vb).y, 5);
    assert.equal(va.sub(vb).x, -1);
    return assert.equal(va.sub(vb).y, -1);
  });
  it('should calculate length', function() {
    var v;
    v = new Core.Vector(3, 4);
    return assert.equal(v.length(), 5);
  });
  return it('should normalize', function() {
    var v;
    v = new Core.Vector(2, 2);
    return assert.equal(v.normalized().length(), 1);
  });
});
